### ISSUE TITLE
section 5: Get-ServerInventory.ps1 gets local data 

### ISSUE THREAD

**Issue by GeorgeQuincy** [PacktPublishing/PowerShell-Toolmaking#1]
Dear author,

Thanks for your code!

Did you notice, that Get-ServerInventory.ps1 gets local data each time instead of getting data from the servers?
Only the Servername is different.

Or am I doing somethin wrong?

At the beginning of the script I changed the -Filter to only get some Servers with "Test1" in its name:

#   $computers = Get-ADComputer -Filter * -ErrorAction Stop | ForEach-Object {$_.Name}  
    $computers = Get-ADComputer -Filter "Name -like 'Test1*'" | ForEach-Object {$_.Name}

But that should do no harm to your code.

kind regards,
George

**Comment by EDockus** [comment]
Hey,

Thanks for this, if you do a PR I'm happy to approve it?

Edgar

**Comment by EDockus** [comment]
I've fixed the code, thanks for bringing this up.
